# -*- coding: utf-8 -*-
"""TASK-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T3njLjcQbpYqcs1TFhH4BrAs8-C92Qde

Create a Personal Introduction Program that asks for user's name, age, and hobby, then displays a friendly welcome message with their information
"""

print("*** Personal Introduction Program ***")
print("* please Enter the details *")
Name = input("Enter Your Name :")
print(f"Hi {Name} please enter the details")
Age = int(input("Enter Your Age :"))
Graduation = input("Enter Your Graduation :")
Hobby = input("Enter Your Hobbies :")
print(f"""{Name} Thank you !!
 for filling the details """)
print(f"""
Hey {Name}! ✨

So cool to have you here!
You're {Age} years young and love {Hobby} — that's awesome! 🎯

Keep shining and have a fantastic day ahead! 😄🌟
""")

